const ENDPOINT = location.hostname === 'localhost'
    ? 'http://127.0.0.1:5000/api/entries'
    : 'https://modlog.rchile.net/api/entries';

const ACTION_MAP = {
    'acceptmoderatorinvite': ['Invite to moderation team accepted', 'user-check'],
    'add_community_topics': ['Added community topic(s)', 'list'],
    'addcontributor': ['Contributor added', 'street-view'],
    'addmoderator': ['Moderator added', 'user-plus'],
    'approvecomment': ['Comment approved', 'calendar-check'],
    'approvelink': ['Post approved', 'calendar-check'],
    'banuser': ['User banned', 'gavel'],
    'collections': ['Did some collections-related stuff', 'object-group'],
    'community_styling': ['Community style changed', 'paint-brush'],
    'community_widgets': ['Community widgets changed', 'boxes'],
    'create_scheduled_post': ['Scheduled post created', 'calendar-plus'],
    'createrule': ['Rule created', 'folder-plus'],
    'delete_scheduled_post': ['Scheduled post deleted', 'calendar-minus'],
    'deleterule': ['Rule removed', 'folder-minus'],
    'distinguishcomment': ['Comment distinguished', 'star'],
    'distinguishpost': ['Post distinguished', 'medal'],
    'edit_post_requirements': ['Post requirements edited', 'tasks'],
    'edit_scheduled_post': ['Scheduled post edited', 'edit'],
    'editflair': ['Post flair edited', 'marker'],
    'editrule': ['Rule edited', 'folder-open'],
    'editsettings': ['Settings edited', 'sliders-h'],
    'events': ['Did some events-related stuff', 'calendar-day'],
    'hidden_award': ['Award hidden', 'star-half-alt'],
    'ignorereports': ['Reports ignored', 'volume-mute'],
    'ignorereportscomment': ['Comment reports ignored', 'volume-mute'],
    'ignorereportspost': ['Post reports ignored', 'volume-mute-alt'],
    'invitemoderator': ['User invited to the moderation team', 'user-shield'],
    'lock': ['Post comments locked', 'lock'],
    'marknsfw': ['Post marked as NSFW', 'hand-holding-water'],
    'markoriginalcontent': ['Post marked as Original Content', 'magic'],
    'modmail_enrollment': ['Modmail enrollment', 'mail-bulk'],
    'muteuser': ['User muted from modmail', 'microphone-slash'],
    'permabanuser': ['User permanently banned', 'skull-crossbones'],
    'remove_community_topics': ['Community topic(s) removed', 'store-slash'],
    'removecomment': ['Comment removed', 'comment-slash'],
    'removelink': ['Post removed', 'unlink'],
    'removelinkauto': ['Post automatically removed', 'unlink'],
    'removemoderator': ['User removed from moderation', 'user-slash'],
    'removewikicontributor': ['Wiki contributor removed', 'user-minus'],
    'reorderrules': ['Rules reordered', 'pencil-ruler'],
    'setcontestmode': ['Contest mode set', 'sort'],
    'setpermissions': ['Permissions set', 'list-alt'],
    'setsuggestedsort': ['Suggestion sort set for post', 'sort'],
    'showcomment': ['Comment shown', 'eye'],
    'spamcomment': ['Comment removed as spam', 'head-side-cough-slash'],
    'spamlink': ['Link post removed as spam', 'shield-virus'],
    'spamlinkcomment': ['Comment removed as spam', 'head-side-cough-slash'],
    'spamlinkpost': ['Post removed as spam', 'shield-virus'],
    'spoiler': ['Marked as spoiler', 'exclamation-triangle'],
    'sticky': ['Stickied', 'sticky-note'],
    'stickycomment': ['Moderator comment stickied', 'sticky-note'],
    'stickydistinguishcomment': ['Comment stickied and distinguished', 'satellite'],
    'stickydistinguishpost': ['Post stickied and distinguished', 'satellite-dish'],
    'stickypost': ['Post stickied', 'sticky-note'],
    'submit_scheduled_post': ['Scheduled post submitted', 'calendar-check'],
    'tempbanend': ['Temporal ban finished', 'user-check'],
    'unbanuser': ['User unbanned', 'user-check'],
    'unignorereports': ['Reports unignored', 'volume-up'],
    'unignorereportscomment': ['Unignored reports for comment', 'volume-up'],
    'unignorereportspost': ['Unignored reports for post', 'volume-up'],
    'unmuteuser': ['User unmuted from modmail', 'head-side-cough'],
    'unlock': ['Post unlocked', 'lock-open'],
    'unspoiler': ['Post unmarked as spoiler', 'glasses'],
    'unstickycomment': ['Comment unstickied', 'map-marked-alt'],
    'unstickypost': ['Post unstickied', 'map-marked-alt'],
    'wikibanned': ['User banned from wiki', 'smoking-ban'],
    'wikicontributor': ['User added as wiki contributor', 'user-edit'],
    'wikipagelisted': ['Wiki page listed', 'file-upload'],
    'wikipermlevel': ['Permission level changed for wiki', 'chess'],
    'wikirevise': ['Wiki page revised', 'th-list'],
    'wikiunbanned': ['User unbanned from wiki', 'user-check']
};

const CONTENT_MAP = {
    'banuser': {'description': 'User: /u/{target_author}, period: {details}.'},
    'permabanuser': {'description': 'User: /u/{target_author}'},
    'removelinkauto': {'description': 'Reason: {details}'},
    'tempbanend': {'description': 'User: /u/{target_author}'},
    'stickydistinguishcomment': {'description': ''},
    'stickycomment': {'description': ''},
    'stickypost': {'description': ''}
}
